INSERT INTO USERS VALUES (1, 'Lesha', '111', '111', 'lesha@gmail.com');
INSERT INTO USERS VALUES (2, 'Vasja', '222', '222', 'vasja@yahoo.com');
INSERT INTO USERS VALUES (3, 'Sasha', '333', '333', 'sasha@gmail.com');

INSERT INTO ROLES VALUES (1, 'Admin');
INSERT INTO ROLES VALUES (2, 'Moder');
INSERT INTO ROLES VALUES (3, 'User');

INSERT INTO USER_ROLE VALUES (1, 1);
INSERT INTO USER_ROLE VALUES (2, 2);
INSERT INTO USER_ROLE VALUES (3, 3);
