spring:
  application:
    name: security-auth
  datasource:
    url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
  h2:
    console:
      enabled: true

h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false

server:
  port: 9991
  contextPath: /auth

security:
  user:
    password: password
  sessions: if-required

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5